<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class PhotoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('photos')->insert([
            ['book_id' => 1, 'filename' => 'demian_1.jpg','is_cover' => true],
            ['book_id' => 1, 'filename' => 'demian_2.jpg', 'is_cover' => false ],
            ['book_id' => 1, 'filename' => 'demian_3.jpg', 'is_cover' => false ],
            ['book_id' => 2, 'filename' => 'genialnapriatelka_1.jpg' ,'is_cover' => true],
            ['book_id' => 2, 'filename' => 'genialnapriatelka_2.jpg', 'is_cover' => false ],
            ['book_id' => 3, 'filename' => 'pribehnovehopriezviska_1.jpg','is_cover' => true],
            ['book_id' => 3, 'filename' => 'pribehnovehopriezviska_2.jpg', 'is_cover' => false ],
            ['book_id' => 4, 'filename' => 'ticoodchadzaju-ticozostavaju_1.jpg','is_cover' => true],
            ['book_id' => 4, 'filename' => 'ticoodchadzaju-ticozostavaju_2.jpg', 'is_cover' => false ],
            ['book_id' => 5, 'filename' => 'pribehsstratenejdcery_1.jpg','is_cover' => true],
            ['book_id' => 5, 'filename' => 'pribehsstratenejdcery_2.jpg', 'is_cover' => false ],
            ['book_id' => 6, 'filename' => 'kafkaontheshore_1.jpg','is_cover' => true],
            ['book_id' => 6, 'filename' => 'kafkaontheshore_2.jpg', 'is_cover' => false ],
            ['book_id' => 6, 'filename' => 'kafkaontheshore_3.jpg', 'is_cover' => false ],
            ['book_id' => 6, 'filename' => 'kafkaontheshore_4.jpg', 'is_cover' => false ],
            ['book_id' => 7, 'filename' => 'velkyzositdokaztretieklamstvo_1.jpg','is_cover' => true],
            ['book_id' => 7, 'filename' => 'velkyzositdokaztretieklamstvo_2.jpg', 'is_cover' => false ],
            ['book_id' => 8, 'filename' => 'nezabudnitenavelrybu_1.jpg','is_cover' => true],
            ['book_id' => 8, 'filename' => 'nezabudnitenavelrybu_2.jpg', 'is_cover' => false ],
            ['book_id' => 8, 'filename' => 'nezabudnitenavelrybu_3.jpg', 'is_cover' => false ],
            ['book_id' => 9, 'filename' => 'cestujemsama_1.jpg','is_cover' => true],
            ['book_id' => 9, 'filename' => 'cestujemsama_2.jpg', 'is_cover' => false ],
            ['book_id' => 9, 'filename' => 'cestujemsama_3.jpg', 'is_cover' => false ],
            ['book_id' => 10, 'filename' => 'mindhunter_1.jpg','is_cover' => true],
            ['book_id' => 10, 'filename' => 'mindhunter_2.jpg', 'is_cover' => false ],
            ['book_id' => 11, 'filename' => 'thethursdaymurderclub_1.jpg','is_cover' => true],
            ['book_id' => 11, 'filename' => 'thethursdaymurderclub_2.jpg', 'is_cover' => false ],
            ['book_id' => 12, 'filename' => 'manwhodiedtwice_1.jpg','is_cover' => true],
            ['book_id' => 12, 'filename' => 'manwhodiedtwice_2.jpg', 'is_cover' => false ],
            ['book_id' => 13, 'filename' => 'thebulletthatmissed_1.jpg','is_cover' => true],
            ['book_id' => 13, 'filename' => 'thebulletthatmissed_2.jpg', 'is_cover' => false ],
            ['book_id' => 14, 'filename' => 'dobreznamenia_1.jpg','is_cover' => true],
            ['book_id' => 14, 'filename' => 'dobreznamenia_2.jpg', 'is_cover' => false ],
            ['book_id' => 14, 'filename' => 'dobreznamenia_3.jpg', 'is_cover' => false ],
            ['book_id' => 15, 'filename' => 'panprstenov1_1.jpg','is_cover' => true],
            ['book_id' => 15, 'filename' => 'panprstenov1_2.jpg', 'is_cover' => false ],
            ['book_id' => 15, 'filename' => 'panprstenov1_3.jpg', 'is_cover' => false ],
            ['book_id' => 16, 'filename' => 'dveveze_1.jpg','is_cover' => true],
            ['book_id' => 16, 'filename' => 'dveveze_2.jpg', 'is_cover' => false ],
            ['book_id' => 16, 'filename' => 'dveveze_3.jpg', 'is_cover' => false ],
            ['book_id' => 17, 'filename' => 'panprstenov3_1.jpg','is_cover' => true],
            ['book_id' => 17, 'filename' => 'panprstenov3_2.jpg', 'is_cover' => false ],
            ['book_id' => 17, 'filename' => 'panprstenov3_3.jpg', 'is_cover' => false ],
            ['book_id' => 18, 'filename' => 'ohenakrv_1.jpg','is_cover' => true],
            ['book_id' => 18, 'filename' => 'ohenakrv_2.jpg', 'is_cover' => false ],
            ['book_id' => 18, 'filename' => 'ohenakrv_3.jpg', 'is_cover' => false ],
            ['book_id' => 19, 'filename' => 'vraniasestka_1.jpg','is_cover' => true],
            ['book_id' => 19, 'filename' => 'vraniasestka_2.jpg', 'is_cover' => false ],
            ['book_id' => 20, 'filename' => 'songofachilles_1.jpg','is_cover' => true],
            ['book_id' => 20, 'filename' => 'songofachilles_2.jpg', 'is_cover' => false ],
            ['book_id' => 21, 'filename' => 'mengelehodievca_1.jpg','is_cover' => true],
            ['book_id' => 21, 'filename' => 'mengelehodievca_2.jpg', 'is_cover' => false ],
            ['book_id' => 21, 'filename' => 'mengelehodievca_3.jpg', 'is_cover' => false ],
            ['book_id' => 22, 'filename' => 'allquietonthewesternfront_1.jpg','is_cover' => true],
            ['book_id' => 22, 'filename' => 'allquietonthewesternfront_2.jpg', 'is_cover' => false ],
            ['book_id' => 23, 'filename' => 'zlodejkaknih_1.jpg','is_cover' => true],
            ['book_id' => 23, 'filename' => 'zlodejkaknih_2.jpg', 'is_cover' => false ],
            ['book_id' => 23, 'filename' => 'zlodejkaknih_3.jpg', 'is_cover' => false ],
            ['book_id' => 24, 'filename' => 'Storočnýstarček,ktorývyliezolzoknaazmizol_1.jpg','is_cover' => true],
            ['book_id' => 24, 'filename' => 'Storočnýstarček,ktorývyliezolzoknaazmizol_2.jpg', 'is_cover' => false ],
            ['book_id' => 24, 'filename' => 'Storočnýstarček,ktorývyliezolzoknaazmizol_3.jpg', 'is_cover' => false ],
            ['book_id' => 25, 'filename' => 'Onákazlivostišťastia_1.jpg',   'is_cover' => true],
            ['book_id' => 25, 'filename' => 'Onákazlivostišťastia_2.jpg', 'is_cover' => false ],
            ['book_id' => 25, 'filename' => 'Onákazlivostišťastia_3.jpg', 'is_cover' => false ],
            ['book_id' => 26, 'filename' => 'hlavaXXII_1.jpg','is_cover' => true],
            ['book_id' => 26, 'filename' => 'hlavaXXII_2.jpg', 'is_cover' => false ],
            ['book_id' => 26, 'filename' => 'hlavaXXII_3.jpg', 'is_cover' => false ],
            ['book_id' => 26, 'filename' => 'hlavaXXII_4.jpg', 'is_cover' => false ],
            ['book_id' => 27, 'filename' => 'obhliadkabytu_1.jpg','is_cover' => true],
            ['book_id' => 27, 'filename' => 'obhliadkabytu_2.jpg', 'is_cover' => false ],
            ['book_id' => 27, 'filename' => 'obhliadkabytu_3.jpg', 'is_cover' => false ],
            ['book_id' => 28, 'filename' => 'dennikodvaznehobojka_1.jpg',   'is_cover' => true],
            ['book_id' => 28, 'filename' => 'dennikodvaznehobojka_2.jpg', 'is_cover' => false ],
            ['book_id' => 29, 'filename' => 'nocchodiacichmumii_1.jpg','is_cover' => true],
            ['book_id' => 29, 'filename' => 'nocchodiacichmumii_2.jpg', 'is_cover' => false ],
            ['book_id' => 30, 'filename' => 'rozpravanieopsikoviamacicke_1.jpg','is_cover' => true],
            ['book_id' => 30, 'filename' => 'rozpravanieopsikoviamacicke_2.jpg', 'is_cover' => false ],
            ['book_id' => 31, 'filename' => 'medvedikpu_1.jpg','is_cover' => true],
            ['book_id' => 31, 'filename' => 'medvedikpu_2.jpg', 'is_cover' => false ],
            ['book_id' => 32, 'filename' => 'malypric_1.jpg','is_cover' => true],
            ['book_id' => 32, 'filename' => 'malypric_2.jpg', 'is_cover' => false ],
            ['book_id' => 33, 'filename' => 'brooklyn_1.jpg','is_cover' => true],
            ['book_id' => 33, 'filename' => 'brooklyn_2.jpg', 'is_cover' => false ],
            ['book_id' => 33, 'filename' => 'brooklyn_3.jpg', 'is_cover' => false ],
            ['book_id' => 34, 'filename' => 'malezeny_1.jpg','is_cover' => true],
            ['book_id' => 34, 'filename' => 'malezeny_2.jpg', 'is_cover' => false ],
            ['book_id' => 34, 'filename' => 'malezeny_3.jpg', 'is_cover' => false ],
            ['book_id' => 35, 'filename' => 'onceuponabrokenheart_1.jpg','is_cover' => true],
            ['book_id' => 35, 'filename' => 'onceuponabrokenheart_2.jpg', 'is_cover' => false ],
            ['book_id' => 36, 'filename' => 'scatteredshowers_1.jpg','is_cover' => true],
            ['book_id' => 36, 'filename' => 'scatteredshowers_2.jpg', 'is_cover' => false ],
            ['book_id' => 37, 'filename' => 'bitunokc5_1.jpg','is_cover' => true],
            ['book_id' => 37, 'filename' => 'bitunokc5_2.jpg', 'is_cover' => false ],
            ['book_id' => 38, 'filename' => 'bravenewworld_1.jpg','is_cover' => true],
            ['book_id' => 38, 'filename' => 'bravenewworld_2.jpg', 'is_cover' => false ],
            ['book_id' => 39, 'filename' => 'cloudcucooland_1.jpg','is_cover' => true],
            ['book_id' => 39, 'filename' => 'cloudcucooland_2.jpg', 'is_cover' => false ],
            ['book_id' => 40, 'filename' => 'fahrenheit_1.jpg','is_cover' => true],
            ['book_id' => 40, 'filename' => 'fahrenheit_2.jpg', 'is_cover' => false ],
            ['book_id' => 41, 'filename' => 'qualityland_1.jpg','is_cover' => true],
            ['book_id' => 41, 'filename' => 'qualityland_2.jpg', 'is_cover' => false ],
            ['book_id' => 42, 'filename' => 'dievcaktoresahralosohnom_1.jpg','is_cover' => true],
            ['book_id' => 42, 'filename' => 'dievcaktoresahralosohnom_2.jpg', 'is_cover' => false ],
            ['book_id' => 42, 'filename' => 'dievcaktoresahralosohnom_3.jpg', 'is_cover' => false ],
            ['book_id' => 43, 'filename' => 'greattalesofhorror_1.jpg','is_cover' => true],
            ['book_id' => 43, 'filename' => 'greattalesofhorror_2.jpg', 'is_cover' => false ],
            ['book_id' => 43, 'filename' => 'greattalesofhorror_3.jpg', 'is_cover' => false ],
            ['book_id' => 44, 'filename' => 'muziktorinenavidiazeny_1.jpg','is_cover' => true],
            ['book_id' => 44, 'filename' => 'muziktorinenavidiazeny_2.jpg', 'is_cover' => false ],
            ['book_id' => 44, 'filename' => 'muziktorinenavidiazeny_3.jpg', 'is_cover' => false ],
            ['book_id' => 45, 'filename' => 'vtedyvlese_1.jpg','is_cover' => true],
            ['book_id' => 45, 'filename' => 'vtedyvlese_2.jpg', 'is_cover' => false ],
            ['book_id' => 45, 'filename' => 'vtedyvlese_3.jpg', 'is_cover' => false ],
            ['book_id' => 46, 'filename' => 'aristotleanddantediscoverthesecretsoftheuniverse_1.jpg','is_cover' => true],
            ['book_id' => 46, 'filename' => 'aristotleanddantediscoverthesecretsoftheuniverse_2.jpg', 'is_cover' => false ],
            ['book_id' => 47, 'filename' => 'AristotleandDanteDiveIntotheWatersoftheWorld_1.jpg','is_cover' => true],
            ['book_id' => 47, 'filename' => 'AristotleandDanteDiveIntotheWatersoftheWorld_2.jpg', 'is_cover' => false ],
            ['book_id' => 48, 'filename' => 'elaenorapark_1.jpg','is_cover' => true],
            ['book_id' => 48, 'filename' => 'elaenorapark_2.jpg', 'is_cover' => false ],
            ['book_id' => 49, 'filename' => 'fanusicka_1.jpg','is_cover' => true],
            ['book_id' => 49,'filename' => 'fanusicka_2.jpg', 'is_cover' => false ],
            ['book_id' => 50, 'filename' => 'release_1.jpg','is_cover' => true],
            ['book_id' => 50, 'filename' => 'release_2.jpg', 'is_cover' => false ],
            ['book_id' => 50, 'filename' => 'release_3.jpg', 'is_cover' => false ],
        ]);
    }
}
